switch to jdk12 and maven
dukke/FXCharts pull request #3
Opened 2019-05-15 10:57 UTC by PtitNoony

2019-05-15 10:59 UTC, PtitNoony commented
Hi, I am very interrested in using your DateAxis in a personal JavaFx App.
Do not hesite to amend the pull request or ask me to make some modifications.
Thank you !

2019-05-19 22:57 UTC, dukke commented
Hi Arnaud,

Thank you very much for taking the time to make this PR.

Have you checked it working? Does this PR work fine in JDK12?

Thanks,

2019-05-20 18:37 UTC, PtitNoony commented
Hi,
with pleasure!
It works using jdk-12.0.1 on Windows-10, using apache-maven-3.5.2.
 Here are the pom dependency I use:

       <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>12.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>12.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.pixelduke</groupId>
            <artifactId>fxcharts</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

2019-05-20 18:37 UTC, PtitNoony commented
![FxCharts_jdk12 0 1](https://user-images.githubusercontent.com/11678429/58044062-224ae300-7b3f-11e9-9dfc-57376ae39d04.PNG)

2019-05-22 01:20 UTC, dukke commented
OK, I'll just glance briefly at the code and merge if everything looks in order.

Unfortunately I don't have time to test it myself at the moment. All my spare time is currently going towards JMetro development, at the moment.

Thank you very much Arnaud!! I'll announce this new addition to FXCharts and I'll credit you for it, of course.

2019-05-30 03:03 UTC, dukke commented
Very sorry for the delay, been very busy lately. I'll be looking at this PR very shortly (probably during the weekend).

Arnaud, thank you very much for this contribution 👍

2019-06-03 00:25 UTC, dukke commented
All seems good @PtitNoony  (Arnaud) with the PR. Seems ready to merge.

Can you just push to a "12.0" branch instead of master? I still want to keep the java8 version for people on java8. Thank you!

2019-06-05 08:57 UTC, PtitNoony commented
Hi, sure, but could you create a 12.0 branch please, I was not able to edit the pull request with a non existing target branch ?
Thank you !

2019-06-07 22:06 UTC, dukke commented
Hi!

Ops sorry, that was dumb should have created the branch first :)

Would like to ask you 2 more things if that's OK with you, if not, no problem:

1 - Put the classes inside package: "com.pixelduke.chart"
2 - Would it be possible for you to use gradle instead of Maven? The problem is that I'm not very proficient with Maven and have a better knowledge of Gradle.

Thanks again!

2019-06-15 09:51 UTC, PtitNoony commented
Hi, 
apologies for the long response time. I am not a gradle user, so I am not sure what I did I ok, please fell free to edit/comment.

2019-06-20 19:22 UTC, dukke requested changes
Hi again Arnaud, 

Thanks again for your time, and for contributing back,

I've submitted a few comments to this PR.

Thanks, kind regards,

2019-06-20 19:22 UTC, dukke commented on build.gradle
> +    compile 'com.googlecode.json-simple:json-simple:1.1.1'
Are you using this library?

2019-06-20 19:22 UTC, dukke commented on build.gradle
> +    main = "com.pixelduke.chart.DemoLauncher"
This class doesn't exist

2019-06-20 19:22 UTC, dukke commented on build.gradle
> +//}
Do you still need this commented out code?

2019-06-20 19:22 UTC, dukke commented on common.gradle
> +    //   http://www.gradle.org/docs/current/userguide/dependency_management.html#sec:repositories
We can remove these comments

2019-06-20 19:22 UTC, dukke commented on common.gradle
> +}
Do we need this task?

2019-06-20 19:22 UTC, dukke commented on common.gradle
> +sourceCompatibility = '1.7'
12?

2019-06-20 19:22 UTC, dukke commented on common.gradle
> +//
Is this build script used anywhere? I don't have actually used a common.gradle file before, reading about it, it seems that you need to put `apply from: '../common.gradle' ` to use it somewhere else?

2019-06-20 19:22 UTC, dukke commented on settings.gradle
> +def subDirs = rootDir.listFiles(new FileFilter() {
I think we don't need the code starting from here all the way to the finish?

2019-06-23 20:11 UTC, PtitNoony commented
thank you for your review. I apologize for the not clean set up, I guess I was not paying enough attention (lack of sleep).
I added a quick fix

2019-06-24 22:29 UTC, dukke commented on settings.gradle
> +def subDirs = rootDir.listFiles(new FileFilter() {
I think we're only missing this?

2019-06-24 22:29 UTC, dukke commented
Hi Arnaud, 

Thanks for the changes, I think we're only missing one code review comment?

Thanks!

2019-07-04 17:30 UTC, PtitNoony commented
Hi,
very sorry for the miss and delay...

2019-07-05 16:26 UTC, dukke approved these changes

2019-07-05 16:26 UTC, dukke commented
Hi,
All seems good now?

2019-07-06 12:25 UTC, PtitNoony commented
Hi, yes it does ! Thank you !

2019-07-09 14:10 UTC, merged

2019-07-09 14:25 UTC, dukke commented
Approved and merged. Thanks Arnaud, I've tweeted about this and thank you in the tweeted for your contribution 👍

2019-07-14 10:28 UTC, PtitNoony commented
Thank you for your patience and your kind, words !
I've been busy with a brand new little thing ! Hopefully I'll be more active in a couple of months.

2019-07-14 17:10 UTC, dukke commented
That would be awesome!

A project I had with a client is also going to probably end soon so I'll have more time for FOSS. 👍